apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-app-backend
  namespace: finance-app
  labels:
    app: finance-app
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-app
      component: backend
  template:
    metadata:
      labels:
        app: finance-app
        component: backend
    spec:
      containers:
      - name: backend
        image: finance-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: finance-app-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: finance-app-secrets
              key: JWT_SECRET
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: finance-app-secrets
              key: TELEGRAM_BOT_TOKEN
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: finance-app-secrets
              key: SMTP_USERNAME
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: finance-app-secrets
              key: SMTP_PASSWORD
        envFrom:
        - configMapRef:
            name: finance-app-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: finance-app-service
  namespace: finance-app
spec:
  selector:
    app: finance-app
    component: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP