apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: financebroke-ingress
  namespace: financebroke
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - financebroke.virhanali.com
    secretName: financebroke-tls
  rules:
  - host: financebroke.virhanali.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: financebroke-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: financebroke-service
            port:
              number: 80